import {Injectable} from 'angular2/core';
import {Observable} from 'rxjs/Observable';
import {withObserver} from './utils';

export class Restaurante {
  constructor(
    public id: number,
    public title: string,
    public abstract: string,
    public details: string,
    public thumbnail: string,
    public thumbnailbig: string,
    public map: string) {}
}

@Injectable()
export class RestauranteService {
  private restaurantes = [
  	new Restaurante(1, 'The Good Burger', 'Especialistas en el mundo de la hamburguesa', '<h3>Descripción</h3><p>ESTA ES LA BUENA HAMBURGUESA. La calidad está aquí. Llamándonos The Good Burger pensarás que somos americanos, o ingleses, pero somos una hamburguesería española que ha cogido la esencia de la hamburguesa clásica con los sabores que más nos gustan aquí. Por eso las elaboramos con ingredientes de la mejor calidad y adaptadas a tu gusto. Porque hamburguesas buenas hay muchas, pero nosotros queremos ser los mejores.</p><h3>Recomendación de platos</h3><div class="row"><div class="col-xs-4 col-md-4 videos"><h3>Hamburguesas</h3><ul><li><img src="img/tgb-burguertgb.png" width="100px" height="auto" />Hamburguesa TGB<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-bbq.png" width="100px" height="auto" />Hamburguesa BBQ<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-pollo.png" width="100px" height="auto" />Hamburguesa de Pollo<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 resources"><h3>Hot Dogs</h3><ul><li><img src="img/tgb-hotdog_California.png" width="100px" height="auto" />Hot Dog California<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-hotdog_NewYork.png" width="100px" height="auto" />Hot Dog New York<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-hotdog_Washington.png" width="100px" height="auto" />Hot Dog Washington<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 popular"><h3>Ensaladas</h3><ul><li><img src="img/tgb-santa_fe.png" width="100px" height="auto" />Ensalada Santa Fe<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-cesar.png" width="100px" height="auto" />Ensalada César<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tgb-huerta.png" width="100px" height="auto" />Ensalada de la Huerta<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div></div>', 'img/TGBGrande.jpg', 'img/tgb-restaurante.jpg', 'https://www.google.com/maps/d/embed?mid=zgD1lMPodVgY.kwc1klKug9fM&hl=en_US'),
  	new Restaurante(2, "Fosters Hollywood",'Sabor americano de alta calida', '<h3>Descripción</h3><p>Foster`s Hollywood es una cadena de restaurantes de comida americana localizada en España, cuyos establecimientos son caracterizables entre los llamados casual restaurants, pero entendidos en una cultura ajena como una suerte de «restaurantes étnicos», como pudieran ser los italianos u orientales.</p><h3>Recomendación de platos</h3><div class="row"><div class="col-xs-4 col-md-4 videos"><h3>Hamburguesas</h3><ul><li><img src="img/foster-black.png" width="100px" height="auto" />Black Label Burguer<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-iberica.png" width="100px" height="auto" />Gran Ibérica Burger<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-wagyu.png" width="100px" height="auto" />Wagyú Burger<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 resources"><h3>Costillas</h3><ul><li><img src="img/foster-missouri.png" width="100px" height="auto" />Missouri ST. Louis<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-kansas.png" width="100px" height="auto" />Kansas Baby Back<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-national.png" width="100px" height="auto" />National Star Ribs<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 popular"><h3>Entrantes</h3><ul><li><img src="img/foster-patatas.png" width="100px" height="auto" />Bacon & Cheese Fries<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-combo.png" width="100px" height="auto" />Hollywood Combo<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/foster-chicken.png" width="100px" height="auto" />Fosters Chicken Pops<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div></div>', 'img/FosterGrande.jpg', 'img/fostershollywood-restaurante.jpg', 'https://www.google.com/maps/d/embed?mid=zgD1lMPodVgY.kwc1klKug9fM&hl=en_US'),
  	new Restaurante(3, 'RIBS','De las mejores parrillas actualmente', '<h3>Descripción</h3><p>Desde 1968. Primer restaurante de España especializado en comida americana. Teniendo restaurantes en toda España. Caracterizados por llevar la eencia de Estados Unidos a todas partes. Famosas parrillas de carbón que cuenta la leyenda que nunca se apagan. El secreto del inconfundible sabor de los platos.</p><h3>Recomendación de platos</h3><div class="row"><div class="col-xs-4 col-md-4 videos"><h3>Hamburguesas</h3><ul><li><img src="img/ribs-angusbeff.png" width="100px" height="auto" />Angus Beef Burguer<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-greatamericanburger.png" width="100px" height="auto" />Great American Burguer<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-luisianaburguer.png" width="100px" height="auto" />Luisiana Burguer<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 resources"><h3>Carnes</h3><ul><li><img src="img/ribs-steakluisiana.png" width="100px" height="auto" />Steak Luisiana<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-entrania.png" width="100px" height="auto" />Entraña<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-chargilledchiquen.png" width="100px" height="auto" />Pollo a la brasa<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 popular"><h3>Postres</h3><ul><li><img src="img/ribs-browniehelado.png" width="100px" height="auto" />Brownie con Helado<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-lemoncake.png" width="100px" height="auto" />Lemon Cake<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/ribs-cookiehelado.png" width="100px" height="auto" />Cookies con Helado<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div></div>', 'img/RibsGrande.jpg', 'img/ribs-restaurante.jpg', 'https://www.google.com/maps/d/embed?mid=zgD1lMPodVgY.kwc1klKug9fM&hl=en_US'),
  	new Restaurante(4, 'La Tagliatella','El toque italiano más fresco', '<h3>Descripción</h3><p>La Tagliatella nace de la experiencia de más de dos décadas de especialización en la cocina tradicional de las regiones del Piemonte, Liguria y Emilia Romagna. Para nosotros la autenticidad y la calidad son los pilares de nuestra manera de entender la gastronomía. Por eso, recorremos cada rincón de la geografía Italiana en busca de los mejores ingredientes, texturas y sabores. </p><h3>Recomendación de platos</h3><div class="row"><div class="col-xs-4 col-md-4 videos"><h3>Pasta</h3><ul><li><img src="img/tag-cannellonidicarne.jpg" width="100px" height="auto" />Canenelloni di Carne<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-farfalleprimavera.jpg" width="100px" height="auto" />Farfalle Primavera<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-penneallaatrabiata.jpg" width="100px" height="auto" />Penne alla Trabiata<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 resources"><h3>Pizzas</h3><ul><li><img src="img/tag-pollobarbecue.jpg" width="100px" height="auto" />Pollo Barbecue<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-portofino.jpg" width="100px" height="auto" />Portofino<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-specialitadellochef.jpg" width="100px" height="auto" />Specialitate dello Chef<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 popular"><h3>Postres</h3><ul><li><img src="img/tag-ciocolattisimo.jpg" width="100px" height="auto" />Ciocolattisimo<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-tortadimascarpone.jpg" width="100px" height="auto" />Torta di Mascarpone<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tag-pizetachocolate.jpg" width="100px" height="auto" />Pizzeta Chocolate<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div></div>', 'img/TagliatellaGrande.jpg', 'img/tag-restaurante.jpg', 'https://www.google.com/maps/d/embed?mid=zgD1lMPodVgY.kwc1klKug9fM&hl=en_US'),
  	new Restaurante(5, 'Telepizza','Uno de los referentes en pizzas', '<h3>Descripción</h3><p>Telepizza es una multinacional española, fundada en 1.987 con carácter de empresa familiar que se ha convertido en pocos años en líder en el sector de reparto a domicilio de comida preparada. Conocida por su calidad y frescura, las pizzas más famosas del país que nos han acompañado durante toda nuestra vida. Cada vez aumenta más su catálogo, proporcionando una grandísima variedad de productos a sus clientes. </p><h3>Recomendación de platos</h3><div class="row"><div class="col-xs-4 col-md-4 videos"><h3>Tradicionales</h3><ul><li><img src="img/tp-carbonara.png" width="100px" height="auto" />Carbonara<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-bbq.png" width="100px" height="auto" />Barbacoa<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-primavera.png" width="100px" height="auto" />Primavera<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 resources"><h3>Amantes de la carne</h3><ul><li><img src="img/tp-iberica.png" width="100px" height="auto" />Ibérica<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-tejana.png" width="100px" height="auto" />Tejana<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-baconcripy.png" width="100px" height="auto" />Bacon Crispy<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div><div class="col-xs-4 col-md-4 popular"><h3>Amantes del Queso</h3><ul><li><img src="img/tp-nachos.png" width="100px" height="auto" />Pizza Nachos<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-delicheese.png" width="100px" height="auto" />Delicheese<hr align="left" noshade="noshade" size="2" width="80%" /></li><li><img src="img/tp-4quesos.png" width="100px" height="auto" />Cuatro Quesos<hr align="left" noshade="noshade" size="2" width="80%" /></li></ul></div></div>', 'img/telepizza.png', 'img/tp-restaurante.jpg', 'https://www.google.com/maps/d/embed?mid=zgD1lMPodVgY.kwc1klKug9fM&hl=en_US')
  ];

  getRestaurantes() {
    return withObserver(this.restaurantes);
  }

  getRestaurante(id: number | string) {
    let restaurante = this.restaurantes.filter(h => h.id === +id)[0]
    return withObserver(new Restaurante(restaurante.id, restaurante.title, restaurante.abstract, restaurante.details, restaurante.thumbnail, restaurante.thumbnailbig, restaurante.map));
  }

  removeRestaurante(restaurante: Restaurante){
    for(let i=0; i<this.restaurantes.length; i++){
        if(this.restaurantes[i].id === restaurante.id){
          this.restaurantes.splice(i,1);
          break;
        }
    }
    return withObserver(undefined);
  }

  saveRestaurante(restaurante: Restaurante){
    if(restaurante.id){
      let oldRestaurante = this.restaurantes.filter(h => h.id === restaurante.id)[0];
      oldRestaurante.title = restaurante.title;
      oldRestaurante.abstract = restaurante.abstract;
      oldRestaurante.details = restaurante.details;
      oldRestaurante.thumbnail = restaurante.thumbnail;
      oldRestaurante.thumbnailbig = restaurante.thumbnailbig;
      oldRestaurante.map = restaurante.map;
    } else {
      restaurante.id = this.restaurantes.length+1;
      this.restaurantes.push(restaurante);
    }
    return withObserver(restaurante);
  }
}
